### ISSUE TITLE
UUIDs in db schema should be char(32) not varchar(255)

### ISSUE THREAD

**Issue by gnewton** [DINA-Web/mediaserver-module#3]
All 128bit UUIDs in hex are 32 chars long:
`ab30899c58a0430585a6bbfa14f89b92`

So it is a fixed length field.

In https://github.com/DINA-Web/mediaserver-module/blob/master/db/src/main/dbschema/db.changelog-0.5.xml  for various tables (`MEDIA`, `IMAGE`, `SOUND`, `VIDEO`, etc) is defined as:
             `<column name="UUID" type="varchar(255)" autoIncrement="false">`
I think it should be
             `<column name="UUID" type="char(32)" autoIncrement="false">`

**Comment by Inkimar** [comment]
https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html
" randomUUID() , Static factory to retrieve a type 4 (pseudo randomly generated) UUID. "
length of 36 . i.e '2dbb201e-c3e7-4c8d-bed4-ed22422d21c3' .

I will make the following  change :
<changeSet id="issue3" author="ingimar">
         <modifyDataType tableName="MEDIA" 
                         columnName="UUID" 
                         newDataType="char(36)" />
    </changeSet>
